module.exports = {
  apps: [
    {
      name: 'petsafe-api',
      cwd: __dirname,
      script: 'dist/main.js',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      max_memory_restart: '250M',
      min_uptime: '10s',
      restart_delay: 5000,
      kill_timeout: 5000,
      time: true,
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        DB_POOL_MAX: 5,
        DB_POOL_MIN: 1,
        DB_IDLE_TIMEOUT_MS: 10000,
        DB_CONNECTION_TIMEOUT_MS: 5000,
        DB_STATEMENT_TIMEOUT_MS: 15000,
        HTTP_JSON_LIMIT: '256kb',
        HTTP_URLENCODED_LIMIT: '256kb',
        HTTP_KEEP_ALIVE_TIMEOUT_MS: 5000,
        HTTP_HEADERS_TIMEOUT_MS: 6000,
        STATIC_ASSETS_CACHE_MAX_AGE: '30d',
        NODE_OPTIONS: '--max-old-space-size=256',
      },
    },
  ],
};
