import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdatePkToInternalUUID1774215376163 implements MigrationInterface {
    name = 'UpdatePkToInternalUUID1774215376163'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // Data-preserving migration: converts a schema that uses UUID primary keys (id uuid)
        // into a schema that uses INTEGER primary keys (id int) + keeps UUIDs in a dedicated
        // `uuid` column for external references.
        //
        // IMPORTANT: This does NOT drop tables or delete application rows.

        const hasPersonas = await queryRunner.hasTable('personas');
        if (!hasPersonas) return;

        const personasIdType = await this.getColumnDataType(queryRunner, 'personas', 'id');
        if (personasIdType !== 'uuid') {
            // Already migrated.
            return;
        }

        await this.convertUuidPkSchemaToIntPkSchema(queryRunner);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        console.log('Down migration not implemented for massive schema refactor. Use backup restoration.');
    }

    private async convertUuidPkSchemaToIntPkSchema(queryRunner: QueryRunner): Promise<void> {
        // Temporarily bypass triggers during structural changes.
        await queryRunner.query('SET session_replication_role = "replica";');

        try {
            const uuidPkTables = await this.getUuidPkIdTables(queryRunner);

            // 1) Add `id_int` to each UUID-PK table, backfill it, and make it unique.
            for (const table of uuidPkTables) {
                const hasIdInt = await queryRunner.hasColumn(table, 'id_int');
                if (!hasIdInt) {
                    await queryRunner.query(`ALTER TABLE "${table}" ADD COLUMN "id_int" integer GENERATED BY DEFAULT AS IDENTITY`);
                }
                await queryRunner.query(`UPDATE "${table}" SET "id_int" = DEFAULT WHERE "id_int" IS NULL`);
                await this.ensureUniqueConstraint(queryRunner, table, `UQ_${table}_id_int`, ['id_int']);
            }

            // 2) Convert all FKs that point to a UUID-PK table's `id` so they point to `id_int`.
            const fkConstraints = await this.getForeignKeysReferencingUuidPkId(queryRunner);
            for (const fk of fkConstraints) {
                await this.convertSingleForeignKey(queryRunner, fk);
            }

            // 3) Swap PKs on each table: old UUID `id` becomes `uuid`, `id_int` becomes new INTEGER `id`.
            for (const table of uuidPkTables) {
                await this.swapPrimaryKeyAndUuid(queryRunner, table);
            }

            // 4) Fix join tables with composite PKs that still reference *_uuid columns.
            // Currently: we keep old UUID FK columns with suffix `_uuid` for traceability.
            // These can be dropped later once you’re confident you don’t need them.
        } finally {
            await queryRunner.query('SET session_replication_role = "origin";');
        }
    }

    private async getColumnDataType(queryRunner: QueryRunner, table: string, column: string): Promise<string | null> {
        const res = await queryRunner.query(
            `SELECT data_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = $1 AND column_name = $2`,
            [table, column],
        );
        return res?.[0]?.data_type ?? null;
    }

    private async hasConstraint(queryRunner: QueryRunner, table: string, constraintName: string): Promise<boolean> {
        const res = await queryRunner.query(
            `SELECT 1
             FROM information_schema.table_constraints
             WHERE table_schema = 'public'
               AND table_name = $1
               AND constraint_name = $2
             LIMIT 1`,
            [table, constraintName],
        );
        return (res ?? []).length > 0;
    }

    private async ensureUniqueConstraint(queryRunner: QueryRunner, table: string, constraintName: string, columns: string[]): Promise<void> {
        const exists = await this.hasConstraint(queryRunner, table, constraintName);
        if (exists) return;

        const cols = columns.map((c) => `"${c}"`).join(', ');
        await queryRunner.query(`ALTER TABLE "${table}" ADD CONSTRAINT "${constraintName}" UNIQUE (${cols})`);
    }

    private async getUuidPkIdTables(queryRunner: QueryRunner): Promise<string[]> {
        // Find all tables in public schema whose PK is a single column named `id` with type uuid.
        const rows = await queryRunner.query(`
            SELECT
              c.relname AS table_name
            FROM pg_constraint pk
            JOIN pg_class c ON c.oid = pk.conrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            JOIN unnest(pk.conkey) WITH ORDINALITY AS k(attnum, ord) ON true
            JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = k.attnum
            JOIN pg_type t ON t.oid = a.atttypid
            WHERE pk.contype = 'p'
              AND n.nspname = 'public'
            GROUP BY c.relname
            HAVING count(*) = 1
               AND max(a.attname) = 'id'
               AND max(t.typname) = 'uuid'
            ORDER BY c.relname;
        `);
        return (rows ?? []).map((r: any) => r.table_name);
    }

    private async getForeignKeysReferencingUuidPkId(queryRunner: QueryRunner): Promise<Array<{ childTable: string; childColumn: string; parentTable: string; constraintName: string; onDelete: string; onUpdate: string; isNullable: boolean }>> {
        // Only handles single-column FKs referencing parent(id uuid).
        const rows = await queryRunner.query(`
            SELECT
              con.conname AS constraint_name,
              child.relname AS child_table,
              child_col.attname AS child_column,
              parent.relname AS parent_table,
              CASE con.confdeltype
                WHEN 'a' THEN 'NO ACTION'
                WHEN 'r' THEN 'RESTRICT'
                WHEN 'c' THEN 'CASCADE'
                WHEN 'n' THEN 'SET NULL'
                WHEN 'd' THEN 'SET DEFAULT'
              END AS on_delete,
              CASE con.confupdtype
                WHEN 'a' THEN 'NO ACTION'
                WHEN 'r' THEN 'RESTRICT'
                WHEN 'c' THEN 'CASCADE'
                WHEN 'n' THEN 'SET NULL'
                WHEN 'd' THEN 'SET DEFAULT'
              END AS on_update,
              (child_col.attnotnull = false) AS is_nullable
            FROM pg_constraint con
            JOIN pg_class child ON child.oid = con.conrelid
            JOIN pg_namespace nchild ON nchild.oid = child.relnamespace
            JOIN pg_class parent ON parent.oid = con.confrelid
            JOIN pg_namespace nparent ON nparent.oid = parent.relnamespace
            JOIN LATERAL unnest(con.conkey) AS child_attnum(attnum) ON true
            JOIN pg_attribute child_col ON child_col.attrelid = child.oid AND child_col.attnum = child_attnum.attnum
            JOIN LATERAL unnest(con.confkey) AS parent_attnum(attnum) ON true
            JOIN pg_attribute parent_col ON parent_col.attrelid = parent.oid AND parent_col.attnum = parent_attnum.attnum
            JOIN pg_type parent_col_type ON parent_col_type.oid = parent_col.atttypid
            WHERE con.contype = 'f'
              AND nchild.nspname = 'public'
              AND nparent.nspname = 'public'
              AND parent_col.attname = 'id'
              AND parent_col_type.typname = 'uuid'
              AND array_length(con.conkey, 1) = 1
              AND array_length(con.confkey, 1) = 1
            ORDER BY child.relname, con.conname;
        `);

        return (rows ?? []).map((r: any) => ({
            childTable: r.child_table,
            childColumn: r.child_column,
            parentTable: r.parent_table,
            constraintName: r.constraint_name,
            onDelete: r.on_delete,
            onUpdate: r.on_update,
            isNullable: !!r.is_nullable,
        }));
    }

    private async convertSingleForeignKey(
        queryRunner: QueryRunner,
        fk: { childTable: string; childColumn: string; parentTable: string; constraintName: string; onDelete: string; onUpdate: string; isNullable: boolean },
    ): Promise<void> {
        const { childTable, childColumn, parentTable, constraintName, onDelete, onUpdate, isNullable } = fk;

        const childColType = await this.getColumnDataType(queryRunner, childTable, childColumn);
        if (childColType !== 'uuid') {
            // Already migrated.
            return;
        }

        const newCol = `${childColumn}__int`;
        const oldCol = `${childColumn}__uuid`;

        const hasNewCol = await queryRunner.hasColumn(childTable, newCol);
        if (!hasNewCol) {
            await queryRunner.query(`ALTER TABLE "${childTable}" ADD COLUMN "${newCol}" integer`);
        }

        // Backfill new integer FK by joining on parent's UUID id.
        await queryRunner.query(`
            UPDATE "${childTable}" c
            SET "${newCol}" = p."id_int"
            FROM "${parentTable}" p
            WHERE c."${childColumn}" = p."id";
        `);

        // Drop FK constraint on UUID column.
        await queryRunner.query(`ALTER TABLE "${childTable}" DROP CONSTRAINT "${constraintName}"`);

        // Preserve old UUID FK value for traceability.
        const alreadyHasOldCol = await queryRunner.hasColumn(childTable, oldCol);
        if (!alreadyHasOldCol) {
            await queryRunner.query(`ALTER TABLE "${childTable}" RENAME COLUMN "${childColumn}" TO "${oldCol}"`);
        }
        await queryRunner.query(`ALTER TABLE "${childTable}" RENAME COLUMN "${newCol}" TO "${childColumn}"`);

        if (!isNullable) {
            // If it was NOT NULL before, enforce it again.
            await queryRunner.query(`ALTER TABLE "${childTable}" ALTER COLUMN "${childColumn}" SET NOT NULL`);
        }

        // Recreate FK constraint now pointing to parent's id_int (unique).
        await queryRunner.query(
            `ALTER TABLE "${childTable}" ADD CONSTRAINT "${constraintName}" FOREIGN KEY ("${childColumn}") REFERENCES "${parentTable}"("id_int") ON DELETE ${onDelete} ON UPDATE ${onUpdate}`,
        );
    }

    private async swapPrimaryKeyAndUuid(queryRunner: QueryRunner, table: string): Promise<void> {
        // At this point, all external references should point to id_int (unique) not id(uuid).
        // We can drop the old PK, rename old UUID id to uuid, and promote id_int to the new PK.

        // Drop primary key constraint
        const pkRows = await queryRunner.query(`
            SELECT con.conname AS pk_name
            FROM pg_constraint con
            JOIN pg_class c ON c.oid = con.conrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE con.contype = 'p'
              AND n.nspname = 'public'
              AND c.relname = $1
            LIMIT 1;
        `, [table]);

        const pkName = pkRows?.[0]?.pk_name;
        if (pkName) {
            await queryRunner.query(`ALTER TABLE "${table}" DROP CONSTRAINT "${pkName}"`);
        }

        const hasUuid = await queryRunner.hasColumn(table, 'uuid');
        if (hasUuid) {
            // If a uuid column already exists, ensure it’s populated.
            await queryRunner.query(`UPDATE "${table}" SET "uuid" = "id" WHERE "uuid" IS NULL`);
            await queryRunner.query(`ALTER TABLE "${table}" DROP COLUMN "id"`);
        } else {
            await queryRunner.query(`ALTER TABLE "${table}" RENAME COLUMN "id" TO "uuid"`);
        }

        // Promote id_int -> id
        await queryRunner.query(`ALTER TABLE "${table}" RENAME COLUMN "id_int" TO "id"`);

        // Recreate PK
        await queryRunner.query(`ALTER TABLE "${table}" ADD PRIMARY KEY ("id")`);

        // Ensure uuid rules
        await queryRunner.query(`ALTER TABLE "${table}" ALTER COLUMN "uuid" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "${table}" ALTER COLUMN "uuid" SET DEFAULT gen_random_uuid()`);
        await this.ensureUniqueConstraint(queryRunner, table, `UQ_${table}_uuid`, ['uuid']);

        // The old unique constraint on id_int is now redundant but harmless; keep it.
    }
}

